language: php

php:
  - '7.3.0'
  - '8.0.0'

before_script:
  - composer update
  - composer install --no-interaction
  - cp .env.travis .env
  - php artisan key:generate

script:
  - php artisan test

notifications:
  - email: noha.waly@vcloud.com
  - on_success: never
  - on_failure: always